name: Publish to npm
on:
  push:
    tags:
      - 'v*.*.*' # Trigger the workflow on push to tags like v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --immutable

      - name: Build (if required)
        run: yarn build

      - name: Publish to npm
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
